### ISSUE TITLE
TERM environment variable not set

### ISSUE THREAD

**Issue by 7starsone** [stylersnico/nmd#1]
Hello,
first, the ss comand on line 143 wasn't found
and I had to write `/usr/sbin/ss`

then on the emails sent to root now remains...
**_TERM environment variable not set**_
(and it's not good to send all those emails every minute, IMO the email must be sent to the owner if there's some ban only)

how to fix the TERM environment variable not set ? thanks

**Comment by 7starsone** [comment]
also, you should make an option to autoempty the log after x days...or suggest a logrotation

**Comment by 7starsone** [comment]
you need to update the cron with
`
... /usr/local/nmd/nmd-agent.sh >> /var/log/nmd-agent.log 2>&1
`
otherwise you send an email to root every minute... I have a huge root spool now

**Comment by stylersnico** [comment]
Hello 7starsone,

What is your OS please ?
Also, thanks for your participation, the program need some adjustments, it's true.

Regards

**Comment by 7starsone** [comment]
;-)
`CentOS Linux 7.1.1503`

thanks

**Comment by stylersnico** [comment]
Thanks, I'm going to check that this we.

**Comment by Tripleoo1** [comment]
Hi,

thanks great skript. Same Issue as 7starsone decribed on CentOS 6.3

is there any Update?

BR

**Comment by stylersnico** [comment]
Hi,
Sorry, I don't have so much time right now.

I make a note to do this this week-end.

Regards,

**Comment by stylersnico** [comment]
New release is up.
Please do a new installation and report any bug :)

**Comment by 7starsone** [comment]
can we do this? (update)
`wget -O- https://raw.githubusercontent.com/stylersnico/nmd/master/centos/update.sh | sh`

**Comment by stylersnico** [comment]
yes

**Comment by 7starsone** [comment]
hello nico,
after the update I thought that all was good... but
at line 146 there still was
`ss -ntu4` so I had to replace it with `/usr/sbin/ss...` again lol
then, **_TERM environment variable not set**_ is still there on log (I don't know what is it)... and also
among the connections/IP in the list there's always "1 Address"
why?

then... an example:
if the network port is 1Gbit and an attacker in that one minute range does a flood of more than 1Gbit...
what happens? by connections you mean TCP ?
thank you
