### ISSUE TITLE
Some questions about nmd found in Ubuntu

### ISSUE THREAD

**Issue by hustcer** [stylersnico/nmd#2]
Hi stylersnico,

Thanks for the great work, I try to run `nmd` on Ubuntu, just to find that:
1. The first time I installed it, it works well, but after 1 hour, it hasn't unban the banned ip before.
2. After restart Ubuntu, the cron job seemed hasn't been run automatically? I just found that the banned ip be unbanned after restart Ubuntu.  So when will the jobs in `/etc/cron.d` be run?
3. Should I add the jobs in `/etc/cron.d` to crontab?

Thanks.

**Comment by stylersnico** [comment]
Hi Hustcer,

1) No unban ? Do you have a script cleaning your /tmp folder ?
2) Normally, the job run every minutes.
It's normal that the previous ip has been unbanned after a reboot since the iptable rule created is not permanent.
3) Yes please, try and tell me if it's work.

Thanks

**Comment by hustcer** [comment]
It's weird that I found it just didn't work sometimes in Ubuntu OS.

**Comment by stylersnico** [comment]
Sometimes ?

Can explain the tests you're doing please ?

**Comment by hustcer** [comment]
I'm not quite sure, it seems that nmd works at the first time been installed, after server been restarted will not work. That's what I found.
